export const silentShowWords = [
  'Lācis', 'Pērtiķis', 'Zilonis', 'Pingvīns', 'Varde', 'Kaķis', 'Suns', 'Čūska', 'Putns', 'Zivs', 'Zirgs', 'Govs', 'Papagailis', 'Ezis', 'Zaķis',
  'Vilks', 'Lapsa', 'Taurenis', 'Zvaigzne', 'Saulespuķe', 'Lietus', 'Sniegavīrs', 'Pērkons', 'Mēness', 'Saulriets', 'Koks', 'Kalns',
  'Jūra', 'Vējš', 'Makšķerēšana', 'Dāvanas iesaiņošana', 'Matu žāvēšana', 'Zupas vārīšana', 'Zobu tīrīšana', 'Kurpju šņorēšana', 'Gulēt',
  'Modinātājs', 'Trauku mazgāšana', 'Grīdas slaucīšana', 'Veļas karināšana', 'Bumbas spēlēšana',
  'Braukšana ar velosipēdu', 'Slidošana', 'Slēpšana', 'Grāmatas lasīšana', 'Fotografēšana', 'Zīmēšana', 'Rakstīšana', 'Telefona zvans',
  'Koku zāģēšana', 'Puķu laistīšana', 'Matu ķemmēšana', 'Roku mazgāšana', 'Ģērbšanās', 'Peldēšana', 'Skriešana', 'Lēkšana', 'Žāvāšanās',
  'Gitarists', 'Šefpavārs', 'Dancotājs', 'Zobārsts', 'Policists', 'Ugunsdzēsējs', 'Ārsts', 'Skolotājs', 'Frizieris', 'Burvis', 'Pirāts', 'Karalis',
  'Supervaronis', 'Klauns', 'Kosmonauts', 'Šoferis', 'Būvnieks', 'Pārdevējs', 'Dziedātājs', 'Detektīvs', 'Pikuls', 'Balerīna', 'Kareivis',
  'Modelis', 'Lietussargs', 'Snovbords', 'Telefons', 'Dators', 'Televizors', 'Pulkstenis', 'Zīmulis', 'Šķēres', 'Mugursoma', 'Spilvens',
  'Segas pārvalks', 'Glāze', 'Karote', 'Dakša', 'Cepure', 'Cimdi', 'Zābaki', 'Brilles', 'Spogulis', 'Hantele',
  'Koferis', 'Lampas slēdzis', 'Svecīte', 'Bumba', 'Ģitāra', 'Klavieres', 'Bungu komplekts', 'Svilpe', 'Mikrofons', 'Saldējums', 'Pica', 'Banāns',
  'Ābols', 'Citrons', 'Ābolu pīrāgs', 'Kafija', 'Tēja', 'Šokolāde', 'Zupa', 'Sviestmaize', 'Desas cepšana', 'Milzu kūka', 'Arbūzs', 'Burkāns',
  'Futbols', 'Basketbols', 'Teniss', 'Bokss', 'Joga', 'Šahs', 'Vindsērfings', 'Boulings', 'Dartu mešana', 'Vingrošana',
  'Telts celšana', 'Šūpošanās', 'Meža pastaiga', 'Pikniks', 'Aukstums', 'Karstums', 'Izsalkums', 'Slāpes', 'Nogurums', 'Bailes', 'Prieks',
  'Dusmas', 'Pārsteigums', 'Smiekli', 'Raudāšana', 'Piepūle', 'Sāpes vēderā', 'Galvassāpes', 'Nieze', 'Automašīna', 'Lidmašīna', 'Kuģis',
  'Vilciens', 'Helikopters', 'Motocikls', 'Skrejritenis', 'Autobuss', 'Raķete', 'Taksometrs', 'Dzimšanas diena', 'Jaunais gads', 'Ziemassvētki',
  'Līgo svētki', 'Kāzas', 'Ballīte', 'Koncerts', 'Diskotēka', 'Salūts', 'Eglītes pušķošana', 'Burbuļu pūšana', 'Svecīšu nopūšana', 'Dāvanas atvēršana',
  'Apskāviens', 'Rokasspiediens', 'Mājieni ar roku', 'Mirkšķināšana', 'Pirkstu knipināšana', 'Šķaudīšana', 'Klepošana', 'Svilpošana',
  'Dziedāšana dušā', 'Solis uz priekšu', 'Atpakaļgaita', 'Vējdzirnavas',
  'Dārgumu meklēšana', 'Milzu solis',
] as const
